// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as Utils from "../src/Utils.res.mjs";
import * as Assert from "./Assert.res.mjs";

Test.test("removes trailing comma and dot", (function () {
        Assert.stringEqual(undefined, Utils.TextUtils.stripPunctuation("Hello, world."), "Hello world");
      }));

Test.test("removes leading and trailing dots", (function () {
        Assert.stringEqual(undefined, Utils.TextUtils.stripPunctuation("...Hello world..."), "Hello world");
      }));

Test.test("removes multiple commas", (function () {
        Assert.stringEqual(undefined, Utils.TextUtils.stripPunctuation("one, two, three,"), "one two three");
      }));

Test.test("preserves question and exclamation marks", (function () {
        Assert.stringEqual(undefined, Utils.TextUtils.stripPunctuation("What?!"), "What?!");
      }));

Test.test("preserves apostrophes in contractions", (function () {
        Assert.stringEqual(undefined, Utils.TextUtils.stripPunctuation("don't, won't, can't."), "don't won't can't");
      }));

Test.test("preserves mixed punctuation at end", (function () {
        Assert.stringEqual(undefined, Utils.TextUtils.stripPunctuation("Wait, what?!"), "Wait what?!");
      }));

Test.test("handles empty string", (function () {
        Assert.stringEqual(undefined, Utils.TextUtils.stripPunctuation(""), "");
      }));

Test.test("handles only dots and commas", (function () {
        Assert.stringEqual(undefined, Utils.TextUtils.stripPunctuation(".,. ,.,"), "");
      }));

Test.test("handles extra spaces with punctuation", (function () {
        Assert.stringEqual(undefined, Utils.TextUtils.stripPunctuation("Hello ... world"), "Hello world");
      }));

export {
  
}
/*  Not a pure module */
