// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as Utils from "../src/Utils.res.mjs";
import * as Assert from "./Assert.res.mjs";

Test.test("parseValidDuration", (function () {
        var duration = Utils.Duration.parseMillisInputToSeconds("00:12,000");
        Assert.okEqual(undefined, duration, 12.0);
      }));

Test.test("parseInvalidDuration", (function () {
        var duration = Utils.Duration.parseMillisInputToSeconds("0012,000");
        Assert.isErr(undefined, duration);
      }));

Test.test("parseRoundedDuration", (function () {
        var duration = Utils.Duration.parseMillisInputToSeconds("00:12,550");
        Assert.okEqual(undefined, duration, 12.55);
      }));

Test.test("formatDuration", (function () {
        var duration = Utils.Duration.formatMillis(12.00);
        Assert.stringEqual(undefined, duration, "00:12,000");
      }));

Test.test("formatRoundedDuration", (function () {
        var duration = Utils.Duration.formatMillis(12.55);
        Assert.stringEqual(undefined, duration, "00:12,550");
      }));

export {
  
}
/*  Not a pure module */
