// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as Assert from "./Assert.res.mjs";
import * as WordTimestamps from "../src/screens/editor/WordTimestamps.res.mjs";

function word(text, startTs, endTs) {
  return {
          text: text,
          timestamp: [
            startTs,
            endTs
          ]
        };
}

function ts(param, endTs) {
  return endTs;
}

function getText(result, idx) {
  return result[idx].text;
}

function getStart(result, idx) {
  return result[idx].timestamp[0];
}

Test.test("tokenize: basic", (function () {
        var result = WordTimestamps.tokenize("hello world");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0], "hello");
        Assert.stringEqual(undefined, result[1], "world");
      }));

Test.test("tokenize: extra spaces", (function () {
        var result = WordTimestamps.tokenize("  hello   world  ");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0], "hello");
        Assert.stringEqual(undefined, result[1], "world");
      }));

Test.test("tokenize: empty string", (function () {
        var result = WordTimestamps.tokenize("");
        Assert.intEqual(undefined, result.length, 0);
      }));

Test.test("tokenize: single word", (function () {
        var result = WordTimestamps.tokenize("hello");
        Assert.intEqual(undefined, result.length, 1);
        Assert.stringEqual(undefined, result[0], "hello");
      }));

Test.test("computeLCS: identical arrays", (function () {
        var result = WordTimestamps.computeLCS([
              "hello",
              "world"
            ], [
              "hello",
              "world"
            ]);
        Assert.intEqual(undefined, result.length, 2);
        Assert.intEqual(undefined, result[0][0], 0);
        Assert.intEqual(undefined, result[0][1], 0);
        Assert.intEqual(undefined, result[1][0], 1);
        Assert.intEqual(undefined, result[1][1], 1);
      }));

Test.test("computeLCS: no matches", (function () {
        var result = WordTimestamps.computeLCS([
              "hello",
              "world"
            ], [
              "goodbye",
              "moon"
            ]);
        Assert.intEqual(undefined, result.length, 0);
      }));

Test.test("computeLCS: partial match", (function () {
        var result = WordTimestamps.computeLCS([
              "hello",
              "world"
            ], [
              "hello",
              "earth"
            ]);
        Assert.intEqual(undefined, result.length, 1);
        Assert.intEqual(undefined, result[0][0], 0);
        Assert.intEqual(undefined, result[0][1], 0);
      }));

Test.test("computeLCS: insertion in middle", (function () {
        var result = WordTimestamps.computeLCS([
              "hello",
              "world"
            ], [
              "hello",
              "beautiful",
              "world"
            ]);
        Assert.intEqual(undefined, result.length, 2);
        Assert.intEqual(undefined, result[0][0], 0);
        Assert.intEqual(undefined, result[0][1], 0);
        Assert.intEqual(undefined, result[1][0], 1);
        Assert.intEqual(undefined, result[1][1], 2);
      }));

Test.test("applyTextEdit: no changes", (function () {
        var words = [
          {
            text: "hello",
            timestamp: [
              0.0,
              0.5
            ]
          },
          {
            text: "world",
            timestamp: [
              0.5,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "hello world");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "hello");
        Assert.stringEqual(undefined, result[1].text, "world");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.5);
      }));

Test.test("applyTextEdit: simple word replacement", (function () {
        var words = [
          {
            text: "hello",
            timestamp: [
              0.0,
              0.5
            ]
          },
          {
            text: "world",
            timestamp: [
              0.5,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "hello earth");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "hello");
        Assert.stringEqual(undefined, result[1].text, "earth");
        Assert.floatEqual(undefined, getStart(result, 1), 0.5);
      }));

Test.test("applyTextEdit: word insertion in middle with gap merges into next match", (function () {
        var words = [
          {
            text: "hello",
            timestamp: [
              0.0,
              0.4
            ]
          },
          {
            text: "world",
            timestamp: [
              0.8,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "hello beautiful world");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "hello");
        Assert.stringEqual(undefined, result[1].text, "beautiful world");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.8);
      }));

Test.test("applyTextEdit: word insertion at START merges with first word", (function () {
        var words = [{
            text: "starting",
            timestamp: [
              0.5,
              1.0
            ]
          }];
        var result = WordTimestamps.applyTextEdit(words, "I'm starting");
        Assert.intEqual(undefined, result.length, 1);
        Assert.stringEqual(undefined, result[0].text, "I'm starting");
        Assert.floatEqual(undefined, getStart(result, 0), 0.5);
      }));

Test.test("applyTextEdit: word insertion at END merges with last word", (function () {
        var words = [{
            text: "ending",
            timestamp: [
              0.0,
              0.5
            ]
          }];
        var result = WordTimestamps.applyTextEdit(words, "ending now");
        Assert.intEqual(undefined, result.length, 1);
        Assert.stringEqual(undefined, result[0].text, "ending now");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
      }));

Test.test("applyTextEdit: multiple words inserted at START", (function () {
        var words = [{
            text: "world",
            timestamp: [
              0.5,
              1.0
            ]
          }];
        var result = WordTimestamps.applyTextEdit(words, "hello beautiful world");
        Assert.intEqual(undefined, result.length, 1);
        Assert.stringEqual(undefined, result[0].text, "hello beautiful world");
        Assert.floatEqual(undefined, getStart(result, 0), 0.5);
      }));

Test.test("applyTextEdit: multiple words inserted at END", (function () {
        var words = [{
            text: "hello",
            timestamp: [
              0.0,
              0.5
            ]
          }];
        var result = WordTimestamps.applyTextEdit(words, "hello beautiful world");
        Assert.intEqual(undefined, result.length, 1);
        Assert.stringEqual(undefined, result[0].text, "hello beautiful world");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
      }));

Test.test("applyTextEdit: word deletion middle", (function () {
        var words = [
          {
            text: "hello",
            timestamp: [
              0.0,
              0.3
            ]
          },
          {
            text: "beautiful",
            timestamp: [
              0.3,
              0.6
            ]
          },
          {
            text: "world",
            timestamp: [
              0.6,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "hello world");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "hello");
        Assert.stringEqual(undefined, result[1].text, "world");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.6);
      }));

Test.test("applyTextEdit: word deletion at START", (function () {
        var words = [
          {
            text: "oh",
            timestamp: [
              0.0,
              0.3
            ]
          },
          {
            text: "hello",
            timestamp: [
              0.3,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "hello");
        Assert.intEqual(undefined, result.length, 1);
        Assert.stringEqual(undefined, result[0].text, "hello");
        Assert.floatEqual(undefined, getStart(result, 0), 0.3);
      }));

Test.test("applyTextEdit: word deletion at END", (function () {
        var words = [
          {
            text: "hello",
            timestamp: [
              0.0,
              0.7
            ]
          },
          {
            text: "there",
            timestamp: [
              0.7,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "hello");
        Assert.intEqual(undefined, result.length, 1);
        Assert.stringEqual(undefined, result[0].text, "hello");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
      }));

Test.test("applyTextEdit: multiple insertions in middle merge into next match", (function () {
        var words = [
          {
            text: "hello",
            timestamp: [
              0.0,
              0.4
            ]
          },
          {
            text: "world",
            timestamp: [
              0.8,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "hello big beautiful world");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "hello");
        Assert.stringEqual(undefined, result[1].text, "big beautiful world");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.8);
      }));

Test.test("applyTextEdit: mixed replacement and middle insertion", (function () {
        var words = [
          {
            text: "hey",
            timestamp: [
              0.0,
              0.3
            ]
          },
          {
            text: "hello",
            timestamp: [
              0.3,
              0.5
            ]
          },
          {
            text: "world",
            timestamp: [
              0.7,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "hey helo beautiful world");
        Assert.intEqual(undefined, result.length, 3);
        Assert.stringEqual(undefined, result[0].text, "hey");
        Assert.stringEqual(undefined, result[1].text, "helo");
        Assert.stringEqual(undefined, result[2].text, "beautiful world");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.3);
        Assert.floatEqual(undefined, getStart(result, 2), 0.7);
      }));

Test.test("applyTextEdit: complete rewrite (0% overlap)", (function () {
        var words = [
          {
            text: "hello",
            timestamp: [
              0.0,
              0.5
            ]
          },
          {
            text: "world",
            timestamp: [
              0.5,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "goodbye moon");
        Assert.intEqual(undefined, result.length, 1);
        Assert.stringEqual(undefined, result[0].text, "goodbye moon");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
      }));

Test.test("applyTextEdit: empty new text", (function () {
        var words = [{
            text: "hello",
            timestamp: [
              0.0,
              1.0
            ]
          }];
        var result = WordTimestamps.applyTextEdit(words, "");
        Assert.intEqual(undefined, result.length, 0);
      }));

Test.test("applyTextEdit: insertions with no gap merge into next match", (function () {
        var words = [
          {
            text: "hello",
            timestamp: [
              0.0,
              0.5
            ]
          },
          {
            text: "world",
            timestamp: [
              0.5,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "hello beautiful world");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "hello");
        Assert.stringEqual(undefined, result[1].text, "beautiful world");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.5);
      }));

Test.test("applyTextEdit: start AND end insertions merge", (function () {
        var words = [{
            text: "hello",
            timestamp: [
              0.3,
              0.7
            ]
          }];
        var result = WordTimestamps.applyTextEdit(words, "oh hello there");
        Assert.intEqual(undefined, result.length, 1);
        Assert.stringEqual(undefined, result[0].text, "oh hello there");
        Assert.floatEqual(undefined, getStart(result, 0), 0.3);
      }));

Test.test("applyTextEdit: complex start merge + middle insert + end merge", (function () {
        var words = [
          {
            text: "hello",
            timestamp: [
              0.0,
              0.3
            ]
          },
          {
            text: "world",
            timestamp: [
              0.7,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "oh hello beautiful world indeed");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "oh hello");
        Assert.stringEqual(undefined, result[1].text, "beautiful world indeed");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.7);
      }));

Test.test("applyTextEdit: single word unchanged", (function () {
        var words = [{
            text: "hello",
            timestamp: [
              0.0,
              1.0
            ]
          }];
        var result = WordTimestamps.applyTextEdit(words, "hello");
        Assert.intEqual(undefined, result.length, 1);
        Assert.stringEqual(undefined, result[0].text, "hello");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
      }));

Test.test("applyTextEdit: punctuation added to word should match and preserve timestamp", (function () {
        var words = [
          {
            text: "Hello",
            timestamp: [
              0.0,
              0.5
            ]
          },
          {
            text: "world",
            timestamp: [
              0.5,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "Hello, world!");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "Hello,");
        Assert.stringEqual(undefined, result[1].text, "world!");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.5);
      }));

Test.test("applyTextEdit: insert word with punctuation", (function () {
        var words = [
          {
            text: "Hello",
            timestamp: [
              0.0,
              0.5
            ]
          },
          {
            text: "world",
            timestamp: [
              0.5,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "Hello, beautiful world!");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "Hello,");
        Assert.stringEqual(undefined, result[1].text, "beautiful world!");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.5);
      }));

Test.test("applyTextEdit: case change should preserve timestamp", (function () {
        var words = [
          {
            text: "hello",
            timestamp: [
              0.0,
              0.5
            ]
          },
          {
            text: "world",
            timestamp: [
              0.5,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "HELLO WORLD");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "HELLO");
        Assert.stringEqual(undefined, result[1].text, "WORLD");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.5);
      }));

Test.test("applyTextEdit: replace word with two words merges into single chunk", (function () {
        var words = [
          {
            text: "Hello",
            timestamp: [
              0.0,
              0.5
            ]
          },
          {
            text: "world",
            timestamp: [
              0.5,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "Hello freaking world");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "Hello");
        Assert.stringEqual(undefined, result[1].text, "freaking world");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.5);
      }));

Test.test("applyTextEdit: replace first word with multiple words", (function () {
        var words = [
          {
            text: "Hello",
            timestamp: [
              0.0,
              0.5
            ]
          },
          {
            text: "world",
            timestamp: [
              0.5,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "Oh hi Hello world");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "Oh hi Hello");
        Assert.stringEqual(undefined, result[1].text, "world");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.5);
      }));

Test.test("applyTextEdit: replace last word with multiple words", (function () {
        var words = [
          {
            text: "Hello",
            timestamp: [
              0.0,
              0.5
            ]
          },
          {
            text: "world",
            timestamp: [
              0.5,
              1.0
            ]
          }
        ];
        var result = WordTimestamps.applyTextEdit(words, "Hello world indeed friend");
        Assert.intEqual(undefined, result.length, 2);
        Assert.stringEqual(undefined, result[0].text, "Hello");
        Assert.stringEqual(undefined, result[1].text, "world indeed friend");
        Assert.floatEqual(undefined, getStart(result, 0), 0.0);
        Assert.floatEqual(undefined, getStart(result, 1), 0.5);
      }));

export {
  word ,
  ts ,
  getText ,
  getStart ,
}
/*  Not a pure module */
