// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ComboboxTsx from "./Combobox.tsx";

var make = ComboboxTsx.Combobox;

var Combobox = {
  make: make
};

export {
  Combobox ,
}
/* make Not a pure module */
