// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DropdownMenu from "./DropdownMenu";

var make = DropdownMenu.DropdownMenu;

var Root = {
  make: make
};

var make$1 = DropdownMenu.DropdownMenuTrigger;

var Trigger = {
  make: make$1
};

var make$2 = DropdownMenu.DropdownMenuContent;

var Content = {
  make: make$2
};

var make$3 = DropdownMenu.DropdownMenuItem;

var Item = {
  make: make$3
};

var make$4 = DropdownMenu.DropdownMenuSeparator;

var Separator = {
  make: make$4
};

var make$5 = DropdownMenu.DropdownMenuLabel;

var Label = {
  make: make$5
};

export {
  Root ,
  Trigger ,
  Content ,
  Item ,
  Separator ,
  Label ,
}
/* make Not a pure module */
