// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as Outline from "@heroicons/react/24/outline";

var MusicalNotesIcon = {};

var FontIcon = {};

var CaptionsIcon = {};

var PlayIcon = {};

var ForwardIcon = {};

function Icons$BackwardIcon(props) {
  return JsxRuntime.jsx(Outline.ArrowUturnRightIcon, {
              color: Caml_option.some(props.color),
              className: Cx.cx([
                    Core__Option.getOr(props.className, ""),
                    "scale-x-[-1]"
                  ]),
              style: Caml_option.some(props.style)
            });
}

var BackwardIcon = {
  make: Icons$BackwardIcon
};

var VolumeIcon = {};

var VolumeLowIcon = {};

var FullScreenIcon = {};

var CollapseIcon = {};

var PauseIcon = {};

var ArrowRightIcon = {};

var BarsCenterLeftIcon = {};

var BarsIcon = {};

var BarsCenterRightIcon = {};

var RenderIcon = {};

var EditIcon = {};

var AlertIcon = {};

function Icons$BorderRadiusIcon(props) {
  var __className = props.className;
  var __color = props.color;
  var color = __color !== undefined ? __color : "currentColor";
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsx("svg", {
              children: JsxRuntime.jsx("path", {
                    d: "M4 14C4 9.58172 7.58172 6 12 6H20",
                    strokeLinecap: "round",
                    strokeWidth: "2"
                  }),
              className: className,
              style: props.style,
              height: "24",
              width: "24",
              fill: "none",
              stroke: color,
              viewBox: "0 0 24 24",
              xmlns: "http://www.w3.org/2000/svg"
            });
}

var BorderRadiusIcon = {
  make: Icons$BorderRadiusIcon
};

var DownloadIcon = {};

var ChatBubbleIcon = {};

function Icons$ProductHuntIcon(props) {
  var __className = props.className;
  var __color = props.color;
  var color = __color !== undefined ? __color : "currentColor";
  var className = __className !== undefined ? __className : "";
  return JsxRuntime.jsxs("svg", {
              children: [
                JsxRuntime.jsx("path", {
                      d: "M26.254 13.128c0 7.253-5.875 13.128-13.128 13.128S-.003 20.382-.003 13.128 5.872 0 13.125 0s13.128 5.875 13.128 13.128",
                      fill: "white"
                    }),
                JsxRuntime.jsx("path", {
                      d: "M14.876 13.128h-3.72V9.2h3.72c1.083 0 1.97.886 1.97 1.97s-.886 1.97-1.97 1.97m0-6.564H8.53v13.128h2.626v-3.938h3.72c2.538 0 4.595-2.057 4.595-4.595s-2.057-4.595-4.595-4.595",
                      fill: color
                    })
              ],
              className: className,
              style: props.style,
              viewBox: "0 0 26.245 26.256",
              xmlns: "http://www.w3.org/2000/svg"
            });
}

var ProductHuntIcon = {
  make: Icons$ProductHuntIcon
};

export {
  MusicalNotesIcon ,
  FontIcon ,
  CaptionsIcon ,
  PlayIcon ,
  ForwardIcon ,
  BackwardIcon ,
  VolumeIcon ,
  VolumeLowIcon ,
  FullScreenIcon ,
  CollapseIcon ,
  PauseIcon ,
  ArrowRightIcon ,
  BarsCenterLeftIcon ,
  BarsIcon ,
  BarsCenterRightIcon ,
  RenderIcon ,
  EditIcon ,
  AlertIcon ,
  BorderRadiusIcon ,
  DownloadIcon ,
  ChatBubbleIcon ,
  ProductHuntIcon ,
}
/* react/jsx-runtime Not a pure module */
