// Generated by ReScript, PLEASE EDIT WITH CARE


var MusicalNotesIcon = {};

var FontIcon = {};

var CaptionsIcon = {};

var PlayIcon = {};

var PlayBackIcon = {};

var VolumeIcon = {};

var VolumeLowIcon = {};

var FullScreenIcon = {};

var CollapseIcon = {};

var PauseIcon = {};

var ArrowRightIcon = {};

var BarsCenterLeftIcon = {};

var BarsIcon = {};

var BarsCenterRightIcon = {};

export {
  MusicalNotesIcon ,
  FontIcon ,
  CaptionsIcon ,
  PlayIcon ,
  PlayBackIcon ,
  VolumeIcon ,
  VolumeLowIcon ,
  FullScreenIcon ,
  CollapseIcon ,
  PauseIcon ,
  ArrowRightIcon ,
  BarsCenterLeftIcon ,
  BarsIcon ,
  BarsCenterRightIcon ,
}
/* No side effect */
