// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.res.mjs";
import * as Hooks from "../hooks/Hooks.res.mjs";
import * as React from "react";
import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Float from "@rescript/core/src/Core__Float.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as ReactDebounce from "rescript-debounce-react/src/ReactDebounce.res.mjs";
import * as React$1 from "@headlessui/react";
import * as JsxRuntime from "react/jsx-runtime";
import * as Webapi__Dom__HtmlInputElement from "rescript-webapi/src/Webapi/Dom/Webapi__Dom__HtmlInputElement.res.mjs";

var Field = {};

var HeadlessLabel = {};

function NumberInput$Label(props) {
  return JsxRuntime.jsx(React$1.Label, {
              htmlFor: props.forId,
              className: Cx.cx([
                    "text-sm/6 ml-1.5 font-medium text-white",
                    Core__Option.getOr(props.className, "")
                  ]),
              children: props.children
            });
}

var Label = {
  HeadlessLabel: HeadlessLabel,
  make: NumberInput$Label
};

var isActiveElement = (function(input) {
    return document.activeElement === input;
  });

function NumberInput(props) {
  var __adornmentClassName = props.adornmentClassName;
  var __adornmentPosition = props.adornmentPosition;
  var adornment = props.adornment;
  var __labelHidden = props.labelHidden;
  var __className = props.className;
  var __step = props.step;
  var __max = props.max;
  var __min = props.min;
  var value = props.value;
  var min = __min !== undefined ? __min : 0;
  var max = __max !== undefined ? __max : 999;
  var step = __step !== undefined ? __step : 1;
  var className = __className !== undefined ? __className : "";
  var labelHidden = __labelHidden !== undefined ? __labelHidden : false;
  var adornmentPosition = __adornmentPosition !== undefined ? __adornmentPosition : "Left";
  var adornmentClassName = __adornmentClassName !== undefined ? __adornmentClassName : "";
  var inputRef = React.useRef(null);
  var id = React.useId();
  var stableOnChange = Hooks.useEvent(props.onChange);
  var debouncedOnChange = ReactDebounce.useDebounced(150, stableOnChange);
  React.useEffect((function () {
          Core__Option.forEach(Core__Option.flatMap(Caml_option.nullable_to_opt(inputRef.current), Webapi__Dom__HtmlInputElement.ofElement), (function (input) {
                  if (!isActiveElement(input)) {
                    input.value = value.toString();
                    return ;
                  }
                  
                }));
        }), [value]);
  var handleChange = function (e) {
    var inputValue = e.currentTarget.value;
    var newValue = Core__Int.fromString(inputValue, undefined);
    if (newValue !== undefined && newValue >= min && newValue <= max) {
      return debouncedOnChange(newValue);
    }
    
  };
  var handleBlur = React.useCallback((function (e) {
          var inputValue = e.currentTarget.value;
          var newValue = Core__Int.fromString(inputValue, undefined);
          if (newValue === undefined) {
            return Core__Option.forEach(Core__Option.flatMap(Caml_option.nullable_to_opt(inputRef.current), Webapi__Dom__HtmlInputElement.ofElement), (function (input) {
                          input.value = value.toString();
                        }));
          }
          var clampedValue = Math.max(Math.min(newValue, max), min);
          stableOnChange(clampedValue);
          Core__Option.forEach(Core__Option.flatMap(Caml_option.nullable_to_opt(inputRef.current), Webapi__Dom__HtmlInputElement.ofElement), (function (input) {
                  input.value = clampedValue.toString();
                }));
        }), [value]);
  var handleKeyDown = function (e) {
    if (e.key === "Enter") {
      return e.currentTarget.blur();
    }
    
  };
  var tmp;
  tmp = adornment !== undefined ? (
      adornmentPosition === "Left" ? "pl-12" : "pr-12"
    ) : "";
  return JsxRuntime.jsxs(React$1.Field, {
              className: className,
              children: [
                JsxRuntime.jsx(NumberInput$Label, {
                      forId: id,
                      children: props.label,
                      className: Cx.cx([labelHidden ? "sr-only" : "whitespace-nowrap"])
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        Core__Option.getOr(Core__Option.map(adornment, (function (adornment) {
                                    var tmp;
                                    tmp = adornmentPosition === "Left" ? "left-0" : "right-0";
                                    return JsxRuntime.jsx("div", {
                                                children: adornment,
                                                className: Cx.cx([
                                                      adornmentClassName,
                                                      "absolute m-1 px-2 inset-y-0 flex justify-center items-center",
                                                      tmp
                                                    ])
                                              });
                                  })), null),
                        JsxRuntime.jsx("input", {
                              ref: Caml_option.some(inputRef),
                              defaultValue: value.toString(),
                              className: Cx.cx([
                                    "block w-full rounded-lg border-none bg-white/10 py-1.5 px-3 text-sm/6 text-white focus:outline-none focus:outline-2 focus:-outline-offset-2 focus:outline-orange-400",
                                    tmp
                                  ]),
                              id: id,
                              max: max.toString(),
                              min: min.toString(),
                              step: step,
                              type: "number",
                              onKeyDown: handleKeyDown,
                              onBlur: handleBlur,
                              onChange: handleChange
                            })
                      ],
                      className: "relative rounded-lg flex"
                    })
              ]
            });
}

function NumberInput$Float(props) {
  var __adornmentClassName = props.adornmentClassName;
  var __adornmentPosition = props.adornmentPosition;
  var adornment = props.adornment;
  var __labelHidden = props.labelHidden;
  var __className = props.className;
  var __step = props.step;
  var __max = props.max;
  var __min = props.min;
  var value = props.value;
  var min = __min !== undefined ? __min : 0.0;
  var max = __max !== undefined ? __max : 1.0;
  var step = __step !== undefined ? __step : 0.1;
  var className = __className !== undefined ? __className : "";
  var labelHidden = __labelHidden !== undefined ? __labelHidden : false;
  var adornmentPosition = __adornmentPosition !== undefined ? __adornmentPosition : "Left";
  var adornmentClassName = __adornmentClassName !== undefined ? __adornmentClassName : "";
  var id = React.useId();
  var inputRef = React.useRef(null);
  var stableOnChange = Hooks.useEvent(props.onChange);
  var debouncedOnChange = ReactDebounce.useDebounced(150, stableOnChange);
  React.useEffect((function () {
          Core__Option.forEach(Core__Option.flatMap(Caml_option.nullable_to_opt(inputRef.current), Webapi__Dom__HtmlInputElement.ofElement), (function (input) {
                  if (!isActiveElement(input)) {
                    input.value = value.toString();
                    return ;
                  }
                  
                }));
        }), [value]);
  var handleChange = function (e) {
    var inputValue = e.currentTarget.value;
    var newValue = Core__Float.fromString(inputValue);
    if (newValue !== undefined && newValue >= min && newValue <= max) {
      return debouncedOnChange(newValue);
    }
    
  };
  var handleBlur = React.useCallback((function (e) {
          var inputValue = e.currentTarget.value;
          var newValue = Core__Float.fromString(inputValue);
          if (newValue === undefined) {
            return Core__Option.forEach(Core__Option.flatMap(Caml_option.nullable_to_opt(inputRef.current), Webapi__Dom__HtmlInputElement.ofElement), (function (input) {
                          input.value = value.toString();
                        }));
          }
          var clampedValue = Math.min(Math.max(newValue, min), max);
          stableOnChange(clampedValue);
          Core__Option.forEach(Core__Option.flatMap(Caml_option.nullable_to_opt(inputRef.current), Webapi__Dom__HtmlInputElement.ofElement), (function (input) {
                  input.value = clampedValue.toString();
                }));
        }), [value]);
  var handleKeyDown = function (e) {
    if (e.key === "Enter") {
      return e.currentTarget.blur();
    }
    
  };
  var tmp;
  tmp = adornment !== undefined ? (
      adornmentPosition === "Left" ? "pl-12" : "pr-12"
    ) : "";
  return JsxRuntime.jsxs(React$1.Field, {
              className: className,
              children: [
                JsxRuntime.jsx(NumberInput$Label, {
                      forId: id,
                      children: props.label,
                      className: Cx.cx([labelHidden ? "sr-only" : "whitespace-nowrap"])
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        Core__Option.getOr(Core__Option.map(adornment, (function (adornment) {
                                    var tmp;
                                    tmp = adornmentPosition === "Left" ? "left-0" : "right-0";
                                    return JsxRuntime.jsx("div", {
                                                children: adornment,
                                                className: Cx.cx([
                                                      adornmentClassName,
                                                      "absolute m-1 px-2 inset-y-0 flex justify-center items-center",
                                                      tmp
                                                    ])
                                              });
                                  })), null),
                        JsxRuntime.jsx("input", {
                              ref: Caml_option.some(inputRef),
                              defaultValue: value.toString(),
                              className: Cx.cx([
                                    "block w-full rounded-lg border-none bg-white/10 py-1.5 px-3 text-sm/6 text-white focus:outline-none focus:outline-2 focus:-outline-offset-2 focus:outline-orange-400",
                                    tmp
                                  ]),
                              id: id,
                              max: max.toString(),
                              min: min.toString(),
                              step: step,
                              type: "number",
                              onKeyDown: handleKeyDown,
                              onBlur: handleBlur,
                              onChange: handleChange
                            })
                      ],
                      className: "relative rounded-lg flex"
                    })
              ]
            });
}

var Float = {
  make: NumberInput$Float
};

var debounceDelay = 150;

var make = NumberInput;

export {
  Field ,
  Label ,
  isActiveElement ,
  debounceDelay ,
  make ,
  Float ,
}
/* Hooks Not a pure module */
