// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as ReactProgress from "@radix-ui/react-progress";

var Root = {};

var Indicator = {};

var RadixProgress = {
  Root: Root,
  Indicator: Indicator
};

function Progress(props) {
  var progress = props.progress;
  return JsxRuntime.jsxs(ReactProgress.Root, {
              className: "relative overflow-hidden border-2 border-white rounded-full w-full h-8",
              value: progress,
              children: [
                JsxRuntime.jsx(ReactProgress.Indicator, {
                      className: "bg-white size-full transition-transform duration-[660ms] ease-[cubic-bezier(0.65,0,0.35,1)]",
                      style: {
                        transform: "translateX(-" + (100 - progress).toString() + "%)"
                      }
                    }),
                JsxRuntime.jsx("span", {
                      children: props.name,
                      className: "absolute top-0.5 left-4 mix-blend-exclusion"
                    }),
                JsxRuntime.jsx("span", {
                      children: progress.toFixed(0) + "%",
                      className: "absolute right-4 top-0.5 mix-blend-exclusion"
                    })
              ]
            });
}

var make = Progress;

export {
  RadixProgress ,
  make ,
}
/* react/jsx-runtime Not a pure module */
