// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactSlider from "@radix-ui/react-slider";

var Root = {};

var Track = {};

var $$Range = {};

var Thumb = {};

var RadixSlider = {
  Root: Root,
  Track: Track,
  $$Range: $$Range,
  Thumb: Thumb
};

function Slider(props) {
  var onValueChange = props.onValueChange;
  var handleChange = React.useCallback((function (newValue) {
          onValueChange(newValue[0]);
        }), [onValueChange]);
  return JsxRuntime.jsxs(ReactSlider.Root, {
              value: [props.value],
              onValueChange: handleChange,
              step: props.step,
              min: props.min,
              max: props.max,
              disabled: Core__Option.getOr(props.disabled, false),
              children: [
                JsxRuntime.jsx(ReactSlider.Track, {
                      children: JsxRuntime.jsx(ReactSlider.Range, {
                            className: "absolute bg-gray-100 rounded-full h-full"
                          }),
                      className: "relative flex-grow h-1 rounded-full bg-slate-800"
                    }),
                JsxRuntime.jsx(ReactSlider.Thumb, {
                      className: "block cursor-grab w-[13px] h-[13px] bg-white transition-transform shadow-xl rounded-full focus:ring-2 ring-offset-1 ring-purple-400 focus:bg-gradient-to-tr from-orange-400 to-orange-600"
                    })
              ],
              className: "relative flex items-center select-none w-full h-4 mx-2"
            });
}

var make = Slider;

export {
  RadixSlider ,
  make ,
}
/* react Not a pure module */
