// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

import "./Spinner.css";
;

function Spinner(props) {
  return JsxRuntime.jsx("span", {
              children: Core__Option.getOr(props.children, null),
              className: "loader inline-flex items-center justify-center"
            });
}

var make = Spinner;

export {
  make ,
}
/*  Not a pure module */
