// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DropdownMenu from "./DropdownMenu.res.mjs";
import * as UseAnalytics from "../hooks/UseAnalytics.res.mjs";
import * as Core__Promise from "@rescript/core/src/Core__Promise.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SubtitleExport from "../utils/subtitleExport";
import * as Outline from "@heroicons/react/24/outline";

function exportToSRT(prim0, prim1) {
  return SubtitleExport.exportToSRT(prim0, prim1);
}

function exportToVTT(prim0, prim1) {
  return SubtitleExport.exportToVTT(prim0, prim1);
}

function SubtitleExportDropdown(props) {
  var videoFileName = props.videoFileName;
  var subtitles = props.subtitles;
  var handleExport = function (format) {
    if (format === "SRT") {
      Core__Promise.$$catch(SubtitleExport.exportToSRT(subtitles, videoFileName), (function (err) {
              UseAnalytics.logException(err, undefined);
              return Promise.resolve();
            }));
      return ;
    }
    Core__Promise.$$catch(SubtitleExport.exportToVTT(subtitles, videoFileName), (function (err) {
            UseAnalytics.logException(err, undefined);
            return Promise.resolve();
          }));
  };
  if (subtitles.length === 0) {
    return null;
  } else {
    return JsxRuntime.jsxs(DropdownMenu.Root.make, {
                children: [
                  JsxRuntime.jsx(DropdownMenu.Trigger.make, {
                        children: props.children,
                        asChild: true
                      }),
                  JsxRuntime.jsxs(DropdownMenu.Content.make, {
                        children: [
                          JsxRuntime.jsx(DropdownMenu.Label.make, {
                                children: "Export as"
                              }),
                          JsxRuntime.jsx(DropdownMenu.Item.make, {
                                children: JsxRuntime.jsxs("span", {
                                      children: [
                                        JsxRuntime.jsx(Outline.ChatBubbleBottomCenterTextIcon, {
                                              className: "mr-2 h-4 w-4"
                                            }),
                                        "SRT Format"
                                      ],
                                      className: "flex items-center"
                                    }),
                                onClick: (function () {
                                    handleExport("SRT");
                                  })
                              }),
                          JsxRuntime.jsx(DropdownMenu.Item.make, {
                                children: JsxRuntime.jsxs("span", {
                                      children: [
                                        JsxRuntime.jsx(Outline.ChatBubbleBottomCenterTextIcon, {
                                              className: "mr-2 h-4 w-4"
                                            }),
                                        "WebVTT Format"
                                      ],
                                      className: "flex items-center"
                                    }),
                                onClick: (function () {
                                    handleExport("VTT");
                                  })
                              })
                        ],
                        sideOffset: props.sideOffset,
                        align: props.align
                      })
                ]
              });
  }
}

var make = SubtitleExportDropdown;

export {
  exportToSRT ,
  exportToVTT ,
  make ,
}
/* DropdownMenu Not a pure module */
