// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ToggleButton from "./ToggleButton";

var make = ToggleButton.ToggleButton;

var Button = {
  make: make
};

var make$1 = ToggleButton.ToggleGroup;

var Group = {
  make: make$1
};

export {
  Button ,
  Group ,
}
/* make Not a pure module */
