// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as ReactTooltip from "@radix-ui/react-tooltip";

var Provider = {};

var Root = {};

var Trigger = {};

var Portal = {};

var Content = {};

var Arrow = {};

var RadixTooltip = {
  Provider: Provider,
  Root: Root,
  Trigger: Trigger,
  Portal: Portal,
  Content: Content,
  Arrow: Arrow
};

function Tooltip(props) {
  return JsxRuntime.jsx(ReactTooltip.Provider, {
              children: JsxRuntime.jsxs(ReactTooltip.Root, {
                    children: [
                      JsxRuntime.jsx(ReactTooltip.Trigger, {
                            children: props.children,
                            asChild: props.asChild
                          }),
                      JsxRuntime.jsx(ReactTooltip.Portal, {
                            children: JsxRuntime.jsxs(ReactTooltip.Content, {
                                  children: [
                                    props.content,
                                    JsxRuntime.jsx(ReactTooltip.Arrow, {
                                          className: "fill-white"
                                        })
                                  ],
                                  className: "data-[state=delayed-open]:data-[side=top]:animate-slideDownAndFade data-[state=delayed-open]:data-[side=right]:animate-slideLeftAndFade data-[state=delayed-open]:data-[side=left]:animate-slideRightAndFade data-[state=delayed-open]:data-[side=bottom]:animate-slideUpAndFade select-none rounded-[4px] bg-white text-black px-[15px] py-[10px] text-[15px] leading-none shadow-[hsl(206_22%_7%_/_35%)_0px_10px_38px_-10px,_hsl(206_22%_7%_/_20%)_0px_10px_20px_-15px] will-change-[transform,opacity]",
                                  sideOffset: 5
                                })
                          })
                    ]
                  })
            });
}

var make = Tooltip;

export {
  RadixTooltip ,
  make ,
}
/* react/jsx-runtime Not a pure module */
