// Generated by ReScript, PLEASE EDIT WITH CARE


var $$AudioParam = {};

var $$AudioBuffer = {};

function setGainValue(gainNode, value, startTime) {
  gainNode.gain.setValueAtTime(value, startTime);
}

var $$AudioNode = {
  setGainValue: setGainValue
};

var $$AudioContext = {};

export {
  $$AudioParam ,
  $$AudioBuffer ,
  $$AudioNode ,
  $$AudioContext ,
}
/* No side effect */
