// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as UseObservable from "../../hooks/useObservable.res.mjs";

var all_font_weights = [
  100,
  200,
  300,
  400,
  500,
  600,
  700,
  800,
  900
];

var defaultBackground = {
  color: "#000000",
  strokeColor: undefined,
  strokeWidth: 1,
  opacity: 0.5,
  paddingX: 16,
  paddingY: 16,
  borderRadius: 32
};

var defaultWordAnimationBackground = {
  color: "#f97316",
  opacity: 1.0,
  paddingX: 6,
  paddingY: 4,
  borderRadius: 4
};

var defaultWordAnimationFont = {
  color: undefined,
  fontWeight: undefined
};

var defaultWordAnimationPop = {
  scale: 1.15
};

var defaultWordAnimation = {
  showBackground: true,
  background: defaultWordAnimationBackground,
  showFont: true,
  font: defaultWordAnimationFont,
  showPop: false,
  pop: defaultWordAnimationPop
};

var defaultPreferences = {
  fontFamily: "Inter",
  fontWeight: 400,
  fontSizePx: 0,
  color: "#ffffff",
  strokeColor: undefined,
  strokeWidth: 1,
  align: "Center",
  showBackground: false,
  background: defaultBackground,
  showWordAnimation: false,
  wordAnimation: defaultWordAnimation
};

var stylePreferencesStorageKey = "subtitler.stylePreferences";

function loadStylePreferences() {
  var storedState = localStorage.getItem(stylePreferencesStorageKey);
  var storedVersion = Core__Option.flatMap(Caml_option.null_to_opt(localStorage.getItem(stylePreferencesStorageKey + ".version")), (function (val) {
          return Core__Int.fromString(val, 10);
        }));
  if (storedState === null) {
    return ;
  }
  if (storedVersion === undefined) {
    return ;
  }
  if (storedVersion !== 2) {
    return ;
  }
  try {
    return JSON.parse(storedState);
  }
  catch (exn){
    return ;
  }
}

function saveStylePreferences(style) {
  var prefs_fontFamily = style.fontFamily;
  var prefs_fontWeight = style.fontWeight;
  var prefs_fontSizePx = style.fontSizePx;
  var prefs_color = style.color;
  var prefs_strokeColor = style.strokeColor;
  var prefs_strokeWidth = style.strokeWidth;
  var prefs_align = style.align;
  var prefs_showBackground = style.showBackground;
  var prefs_background = style.background;
  var prefs_showWordAnimation = style.showWordAnimation;
  var prefs_wordAnimation = style.wordAnimation;
  var prefs = {
    fontFamily: prefs_fontFamily,
    fontWeight: prefs_fontWeight,
    fontSizePx: prefs_fontSizePx,
    color: prefs_color,
    strokeColor: prefs_strokeColor,
    strokeWidth: prefs_strokeWidth,
    align: prefs_align,
    showBackground: prefs_showBackground,
    background: prefs_background,
    showWordAnimation: prefs_showWordAnimation,
    wordAnimation: prefs_wordAnimation
  };
  localStorage.setItem(stylePreferencesStorageKey, Core__Option.getOr(JSON.stringify(prefs), ""));
  localStorage.setItem(stylePreferencesStorageKey + ".version", String(2));
}

function MakeRendererObservable(Ctx) {
  var width = Ctx.videoMeta.width > Ctx.videoMeta.height ? Ctx.videoMeta.width / 4 | 0 : ((Ctx.videoMeta.width / 3 | 0) << 1);
  var center = (Ctx.videoMeta.width / 2 | 0) - (width / 2 | 0) | 0;
  var defaultFontSizePx = Ctx.videoMeta.height / 30 | 0;
  var savedPrefs = loadStylePreferences();
  var initial_y = Ctx.videoMeta.width > Ctx.videoMeta.height ? Ctx.videoMeta.height - (Ctx.videoMeta.height / 6 | 0) | 0 : Ctx.videoMeta.height / 7 | 0;
  var initial_fontFamily = Core__Option.mapOr(savedPrefs, "Inter", (function (p) {
          return p.fontFamily;
        }));
  var initial_fontWeight = Core__Option.mapOr(savedPrefs, 400, (function (p) {
          return p.fontWeight;
        }));
  var initial_fontSizePx = Core__Option.getOr(Core__Option.filter(Core__Option.map(savedPrefs, (function (p) {
                  return p.fontSizePx;
                })), (function (size) {
              return size > 0;
            })), defaultFontSizePx);
  var initial_color = Core__Option.mapOr(savedPrefs, "#ffffff", (function (p) {
          return p.color;
        }));
  var initial_strokeColor = Core__Option.flatMap(savedPrefs, (function (p) {
          return p.strokeColor;
        }));
  var initial_strokeWidth = Core__Option.mapOr(savedPrefs, 1, (function (p) {
          return p.strokeWidth;
        }));
  var initial_align = Core__Option.mapOr(savedPrefs, "Center", (function (p) {
          return p.align;
        }));
  var initial_blockSize = {
    width: width,
    height: defaultFontSizePx
  };
  var initial_showBackground = Core__Option.mapOr(savedPrefs, false, (function (p) {
          return p.showBackground;
        }));
  var initial_background = Core__Option.mapOr(savedPrefs, defaultBackground, (function (p) {
          return p.background;
        }));
  var initial_showWordAnimation = Core__Option.mapOr(savedPrefs, false, (function (p) {
          return p.showWordAnimation;
        }));
  var initial_wordAnimation = Core__Option.mapOr(savedPrefs, defaultWordAnimation, (function (p) {
          return p.wordAnimation;
        }));
  var initial = {
    x: center,
    y: initial_y,
    fontFamily: initial_fontFamily,
    fontWeight: initial_fontWeight,
    fontSizePx: initial_fontSizePx,
    color: initial_color,
    strokeColor: initial_strokeColor,
    strokeWidth: initial_strokeWidth,
    align: initial_align,
    blockSize: initial_blockSize,
    fontVariants: all_font_weights,
    showBackground: initial_showBackground,
    background: initial_background,
    showWordAnimation: initial_showWordAnimation,
    wordAnimation: initial_wordAnimation
  };
  var reducer = function (state, action) {
    var newState;
    if (typeof action !== "object") {
      switch (action) {
        case "ResetFontVariants" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: state.blockSize,
              fontVariants: all_font_weights,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "ToggleBackground" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: state.blockSize,
              fontVariants: state.fontVariants,
              showBackground: !state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "ToggleWordAnimation" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: state.blockSize,
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: !state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        
      }
    } else {
      switch (action.TAG) {
        case "Resize" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: action._0,
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "SetAlign" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: action._0,
              blockSize: state.blockSize,
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "SetBackground" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: state.blockSize,
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: action._0,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "SetBlockHeight" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: {
                width: state.blockSize.width,
                height: action._0
              },
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "SetBlockWidth" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: {
                width: action._0,
                height: state.blockSize.height
              },
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "SetColor" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: action._0,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: state.blockSize,
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "SetFontFamily" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: action._0,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: state.blockSize,
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "SetFontSizePx" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: action._0,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: state.blockSize,
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "SetFontVariants" :
            var variants = action._0;
            newState = variants.includes(state.fontWeight) ? ({
                  x: state.x,
                  y: state.y,
                  fontFamily: state.fontFamily,
                  fontWeight: state.fontWeight,
                  fontSizePx: state.fontSizePx,
                  color: state.color,
                  strokeColor: state.strokeColor,
                  strokeWidth: state.strokeWidth,
                  align: state.align,
                  blockSize: state.blockSize,
                  fontVariants: variants,
                  showBackground: state.showBackground,
                  background: state.background,
                  showWordAnimation: state.showWordAnimation,
                  wordAnimation: state.wordAnimation
                }) : ({
                  x: state.x,
                  y: state.y,
                  fontFamily: state.fontFamily,
                  fontWeight: variants.includes(400) ? 400 : Core__Option.getOr(variants[0], 400),
                  fontSizePx: state.fontSizePx,
                  color: state.color,
                  strokeColor: state.strokeColor,
                  strokeWidth: state.strokeWidth,
                  align: state.align,
                  blockSize: state.blockSize,
                  fontVariants: variants,
                  showBackground: state.showBackground,
                  background: state.background,
                  showWordAnimation: state.showWordAnimation,
                  wordAnimation: state.wordAnimation
                });
            break;
        case "SetFontWeight" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: action._0,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: state.blockSize,
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "SetPosition" :
            newState = {
              x: action._0,
              y: action._1,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: state.blockSize,
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "SetStrokeColor" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: action._0,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: state.blockSize,
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "SetStrokeWidth" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: action._0,
              align: state.align,
              blockSize: state.blockSize,
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: state.wordAnimation
            };
            break;
        case "SetWordAnimation" :
            newState = {
              x: state.x,
              y: state.y,
              fontFamily: state.fontFamily,
              fontWeight: state.fontWeight,
              fontSizePx: state.fontSizePx,
              color: state.color,
              strokeColor: state.strokeColor,
              strokeWidth: state.strokeWidth,
              align: state.align,
              blockSize: state.blockSize,
              fontVariants: state.fontVariants,
              showBackground: state.showBackground,
              background: state.background,
              showWordAnimation: state.showWordAnimation,
              wordAnimation: action._0
            };
            break;
        
      }
    }
    saveStylePreferences(newState);
    return newState;
  };
  return UseObservable.MakeObserver({
              initial: initial,
              reducer: reducer
            });
}

var stylePreferencesVersion = 2;

export {
  all_font_weights ,
  defaultBackground ,
  defaultWordAnimationBackground ,
  defaultWordAnimationFont ,
  defaultWordAnimationPop ,
  defaultWordAnimation ,
  defaultPreferences ,
  stylePreferencesStorageKey ,
  stylePreferencesVersion ,
  loadStylePreferences ,
  saveStylePreferences ,
  MakeRendererObservable ,
}
/* UseObservable Not a pure module */
