// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDebounce from "rescript-debounce-react/src/ReactDebounce.res.mjs";
import * as Webapi__Dom__Window from "rescript-webapi/src/Webapi/Dom/Webapi__Dom__Window.res.mjs";
import * as Webapi__Dom__EventTarget from "rescript-webapi/src/Webapi/Dom/Webapi__Dom__EventTarget.res.mjs";

var DocumentEvent = Webapi__Dom__EventTarget.Impl({});

function getDimensions(param) {
  return {
          width: window.innerWidth,
          height: window.innerHeight
        };
}

function useDimensions() {
  var match = React.useState(getDimensions);
  var setDimensions = match[1];
  var handleResize = ReactDebounce.useDebounced(200, (function (param) {
          setDimensions(getDimensions);
        }));
  React.useLayoutEffect((function () {
          window.addEventListener("resize", handleResize);
          return (function () {
                    window.removeEventListener("resize", handleResize);
                  });
        }), []);
  return match[0];
}

export {
  DocumentEvent ,
  getDimensions ,
  useDimensions ,
}
/* DocumentEvent Not a pure module */
