// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function serdeString_parse(str) {
  return str;
}

function serdeString_serialize(str) {
  return str;
}

var serdeString = {
  parse: serdeString_parse,
  serialize: serdeString_serialize
};

function useStickyState(persistKey, version, defaultValue, serde) {
  var match = React.useState(function () {
        var storedState = localStorage.getItem(persistKey);
        var storedVersion = Core__Option.flatMap(Caml_option.null_to_opt(localStorage.getItem(persistKey + ".version")), (function (val) {
                return Core__Int.fromString(val, 10);
              }));
        if (storedState === null) {
          return defaultValue;
        }
        if (storedVersion === undefined) {
          return defaultValue;
        }
        if (storedVersion !== version) {
          return defaultValue;
        }
        try {
          return serde.parse(storedState);
        }
        catch (exn){
          return defaultValue;
        }
      });
  var setRawState = match[1];
  var setState = React.useCallback((function (newState) {
          localStorage.setItem(persistKey, serde.serialize(newState));
          localStorage.setItem(persistKey + ".version", String(version));
          setRawState(function (param) {
                return newState;
              });
        }), []);
  return [
          match[0],
          setState
        ];
}

export {
  serdeString ,
  useStickyState ,
}
/* react Not a pure module */
