// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.res.mjs";
import * as Hooks from "../../../hooks/Hooks.res.mjs";
import * as Icons from "../../../ui/Icons.res.mjs";
import * as Input from "../../../ui/Input.res.mjs";
import * as Utils from "../../../Utils.res.mjs";
import * as React from "react";
import * as Slider from "../../../ui/Slider.res.mjs";
import * as Combobox from "../../../ui/Combobox.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as NumberInput from "../../../ui/NumberInput.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as ToggleButton from "../../../ui/ToggleButton.res.mjs";
import * as ToggleSwitch from "../../../ui/ToggleSwitch.res.mjs";
import * as EditorContext from "../EditorContext.res.mjs";
import * as ReactFontPicker from "../../../bindings/ReactFontPicker.res.mjs";
import * as React$1 from "@headlessui/react";
import * as JsxRuntime from "react/jsx-runtime";
import * as Outline from "@heroicons/react/24/outline";

function formatFontWeight(weight) {
  switch (weight) {
    case 100 :
        return "Thin";
    case 200 :
        return "Extra Light";
    case 300 :
        return "Light";
    case 400 :
        return "Regular";
    case 500 :
        return "Medium";
    case 600 :
        return "Semi Bold";
    case 700 :
        return "Bold";
    case 800 :
        return "Extra Bold";
    case 900 :
        return "Black";
    
  }
}

var adornmentClassName = "font-mono rounded-md m-1 bg-zinc-500 px-3 inset-y-0";

var make = Utils.neverRerender(function (props) {
      var id = React.useId();
      var editorContext = EditorContext.useEditorContext();
      var match = editorContext.useStyle();
      var dispatch = match[1];
      var style = match[0];
      return JsxRuntime.jsx("div", {
                  children: JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsx(NumberInput.make, {
                                        value: style.x,
                                        onChange: (function (val) {
                                            dispatch({
                                                  TAG: "SetPosition",
                                                  _0: val,
                                                  _1: style.y
                                                });
                                          }),
                                        label: "X coordinate",
                                        min: 0,
                                        max: 999,
                                        className: "w-full",
                                        labelHidden: true,
                                        adornment: "X",
                                        adornmentClassName: adornmentClassName
                                      }),
                                  JsxRuntime.jsx(NumberInput.make, {
                                        value: style.y,
                                        onChange: (function (val) {
                                            dispatch({
                                                  TAG: "SetPosition",
                                                  _0: style.x,
                                                  _1: val
                                                });
                                          }),
                                        label: "Y coordinate",
                                        min: 0,
                                        max: 999,
                                        className: "w-full",
                                        labelHidden: true,
                                        adornment: "Y",
                                        adornmentClassName: adornmentClassName
                                      }),
                                  JsxRuntime.jsx(NumberInput.make, {
                                        value: style.blockSize.width,
                                        onChange: (function (val) {
                                            dispatch({
                                                  TAG: "SetBlockWidth",
                                                  _0: val
                                                });
                                          }),
                                        label: "Width",
                                        min: 0,
                                        max: 999,
                                        className: "w-full",
                                        labelHidden: true,
                                        adornment: "W",
                                        adornmentClassName: adornmentClassName
                                      }),
                                  JsxRuntime.jsx(NumberInput.make, {
                                        value: style.blockSize.height,
                                        onChange: (function (val) {
                                            dispatch({
                                                  TAG: "SetBlockHeight",
                                                  _0: val
                                                });
                                          }),
                                        label: "Height",
                                        min: 0,
                                        max: 999,
                                        className: "w-full",
                                        labelHidden: true,
                                        adornment: "H",
                                        adornmentClassName: adornmentClassName
                                      })
                                ],
                                className: "rounded-xl focus-within:border-zinc-500 border transition-colors border-transparent grid grid-cols-2 gap-2 bg-white/5 p-3 w-full"
                              }),
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsxs(React$1.Field, {
                                        className: "col-span-3",
                                        children: [
                                          JsxRuntime.jsx(Input.Label.make, {
                                                forId: "font-picker" + id,
                                                children: "Font",
                                                className: "whitespace-nowrap"
                                              }),
                                          JsxRuntime.jsx(ReactFontPicker.make, {
                                                inputId: "font-picker" + id,
                                                initialFont: style.fontFamily,
                                                onFontLoad: Hooks.useEvent(function (val) {
                                                      dispatch({
                                                            TAG: "SetFontFamily",
                                                            _0: val
                                                          });
                                                    }),
                                                onFontVariantInfo: Hooks.useEvent(function (variants) {
                                                      dispatch(variants.length > 0 ? ({
                                                                TAG: "SetFontVariants",
                                                                _0: variants
                                                              }) : "ResetFontVariants");
                                                    })
                                              })
                                        ]
                                      }),
                                  JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsx(Input.make, {
                                                label: "Fill",
                                                value: style.color,
                                                type_: "color",
                                                className: "w-full col-span-1 flex-1",
                                                onChange: (function (value) {
                                                    dispatch({
                                                          TAG: "SetColor",
                                                          _0: value
                                                        });
                                                  })
                                              }),
                                          JsxRuntime.jsx(Input.make, {
                                                label: "Stroke",
                                                value: Core__Option.getOr(style.strokeColor, style.color),
                                                type_: "color",
                                                className: "w-full col-span-1 flex-1",
                                                onChange: (function (value) {
                                                    dispatch({
                                                          TAG: "SetStrokeColor",
                                                          _0: value
                                                        });
                                                  })
                                              }),
                                          JsxRuntime.jsx(NumberInput.make, {
                                                value: style.strokeWidth,
                                                onChange: (function (strokeWidth) {
                                                    dispatch({
                                                          TAG: "SetStrokeWidth",
                                                          _0: strokeWidth
                                                        });
                                                  }),
                                                label: "width",
                                                min: 0,
                                                max: 999,
                                                adornmentClassName: adornmentClassName
                                              })
                                        ],
                                        className: "flex gap-2 col-span-3"
                                      }),
                                  JsxRuntime.jsxs(React$1.Field, {
                                        className: "col-span-3",
                                        children: [
                                          JsxRuntime.jsx(Input.Label.make, {
                                                children: "Font weight",
                                                className: "whitespace-nowrap"
                                              }),
                                          JsxRuntime.jsx(Combobox.make, {
                                                options: style.fontVariants,
                                                selected: style.fontWeight,
                                                formatValue: formatFontWeight,
                                                setSelected: (function (value) {
                                                    Core__Option.forEach(value, (function (value) {
                                                            dispatch({
                                                                  TAG: "SetFontWeight",
                                                                  _0: value
                                                                });
                                                          }));
                                                  }),
                                                filter: (function (value) {
                                                    return function (item) {
                                                      return formatFontWeight(item).toLowerCase().includes(value);
                                                    };
                                                  })
                                              })
                                        ]
                                      }),
                                  JsxRuntime.jsx(NumberInput.make, {
                                        value: style.fontSizePx,
                                        onChange: (function (val) {
                                            dispatch({
                                                  TAG: "SetFontSizePx",
                                                  _0: val
                                                });
                                          }),
                                        label: "Size",
                                        min: 0,
                                        max: 999,
                                        className: "min-w-[4ch]"
                                      }),
                                  JsxRuntime.jsxs(React$1.Field, {
                                        className: "col-span-2",
                                        children: [
                                          JsxRuntime.jsx(Input.Label.make, {
                                                forId: "",
                                                children: "Text align",
                                                className: "whitespace-nowrap"
                                              }),
                                          JsxRuntime.jsxs(ToggleButton.Group.make, {
                                                children: [
                                                  JsxRuntime.jsx(ToggleButton.Button.make, {
                                                        children: Caml_option.some(JsxRuntime.jsx(Outline.Bars3BottomLeftIcon, {
                                                                  className: "size-4"
                                                                })),
                                                        value: "Left"
                                                      }),
                                                  JsxRuntime.jsx(ToggleButton.Button.make, {
                                                        children: Caml_option.some(JsxRuntime.jsx(Outline.Bars3Icon, {
                                                                  className: "size-4"
                                                                })),
                                                        value: "Center"
                                                      }),
                                                  JsxRuntime.jsx(ToggleButton.Button.make, {
                                                        children: Caml_option.some(JsxRuntime.jsx(Outline.Bars3BottomRightIcon, {
                                                                  className: "size-4"
                                                                })),
                                                        value: "Right"
                                                      })
                                                ],
                                                onChange: (function (value) {
                                                    dispatch({
                                                          TAG: "SetAlign",
                                                          _0: value
                                                        });
                                                  }),
                                                value: style.align
                                              })
                                        ]
                                      })
                                ],
                                className: "rounded-xl focus-within:border-zinc-500 border transition-colors border-transparent grid grid-cols-3 md:grid-cols-6 gap-2 bg-white/5 p-3 w-full"
                              }),
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsx(ToggleSwitch.make, {
                                                labelId: "background-title",
                                                enabled: style.showBackground,
                                                onChange: (function (param) {
                                                    dispatch("ToggleBackground");
                                                  })
                                              }),
                                          JsxRuntime.jsx("h3", {
                                                children: "Background",
                                                id: "background-title"
                                              })
                                        ],
                                        className: "flex items-center gap-4"
                                      }),
                                  JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsx(Input.make, {
                                                label: "Fill",
                                                value: style.background.color,
                                                type_: "color",
                                                className: "w-full col-span-1 flex-1",
                                                onChange: (function (value) {
                                                    var init = style.background;
                                                    dispatch({
                                                          TAG: "SetBackground",
                                                          _0: {
                                                            color: value,
                                                            strokeColor: init.strokeColor,
                                                            strokeWidth: init.strokeWidth,
                                                            opacity: init.opacity,
                                                            paddingX: init.paddingX,
                                                            paddingY: init.paddingY,
                                                            borderRadius: init.borderRadius
                                                          }
                                                        });
                                                  })
                                              }),
                                          JsxRuntime.jsx(NumberInput.Float.make, {
                                                value: style.background.opacity,
                                                onChange: (function (opacity) {
                                                    var init = style.background;
                                                    dispatch({
                                                          TAG: "SetBackground",
                                                          _0: {
                                                            color: init.color,
                                                            strokeColor: init.strokeColor,
                                                            strokeWidth: init.strokeWidth,
                                                            opacity: opacity,
                                                            paddingX: init.paddingX,
                                                            paddingY: init.paddingY,
                                                            borderRadius: init.borderRadius
                                                          }
                                                        });
                                                  }),
                                                label: "Opacity",
                                                min: 0.0,
                                                max: 1.0,
                                                step: 0.1,
                                                className: "w-full col-span-1 flex-1"
                                              }),
                                          JsxRuntime.jsx(Input.make, {
                                                label: "Stroke",
                                                value: style.background.color,
                                                type_: "color",
                                                className: "w-full col-span-1 flex-1",
                                                onChange: (function (value) {
                                                    var init = style.background;
                                                    dispatch({
                                                          TAG: "SetBackground",
                                                          _0: {
                                                            color: init.color,
                                                            strokeColor: value,
                                                            strokeWidth: init.strokeWidth,
                                                            opacity: init.opacity,
                                                            paddingX: init.paddingX,
                                                            paddingY: init.paddingY,
                                                            borderRadius: init.borderRadius
                                                          }
                                                        });
                                                  })
                                              }),
                                          JsxRuntime.jsx(NumberInput.make, {
                                                value: style.background.strokeWidth,
                                                onChange: (function (strokeWidth) {
                                                    var init = style.background;
                                                    dispatch({
                                                          TAG: "SetBackground",
                                                          _0: {
                                                            color: init.color,
                                                            strokeColor: init.strokeColor,
                                                            strokeWidth: strokeWidth,
                                                            opacity: init.opacity,
                                                            paddingX: init.paddingX,
                                                            paddingY: init.paddingY,
                                                            borderRadius: init.borderRadius
                                                          }
                                                        });
                                                  }),
                                                label: "width",
                                                min: 0,
                                                max: 999,
                                                className: "w-full",
                                                adornmentClassName: adornmentClassName
                                              }),
                                          JsxRuntime.jsx(NumberInput.make, {
                                                value: style.background.borderRadius,
                                                onChange: (function (borderRadius) {
                                                    var init = style.background;
                                                    dispatch({
                                                          TAG: "SetBackground",
                                                          _0: {
                                                            color: init.color,
                                                            strokeColor: init.strokeColor,
                                                            strokeWidth: init.strokeWidth,
                                                            opacity: init.opacity,
                                                            paddingX: init.paddingX,
                                                            paddingY: init.paddingY,
                                                            borderRadius: borderRadius
                                                          }
                                                        });
                                                  }),
                                                label: "Border radius",
                                                min: 0,
                                                max: 999,
                                                className: "w-full col-span-2",
                                                adornment: Caml_option.some(JsxRuntime.jsx(Icons.BorderRadiusIcon.make, {
                                                          color: "white",
                                                          className: "size-4"
                                                        })),
                                                adornmentClassName: "font-mono rounded-md bg-zinc-500 px-2.5 inset-y-0"
                                              }),
                                          JsxRuntime.jsx(NumberInput.make, {
                                                value: style.background.paddingX,
                                                onChange: (function (paddingX) {
                                                    var init = style.background;
                                                    dispatch({
                                                          TAG: "SetBackground",
                                                          _0: {
                                                            color: init.color,
                                                            strokeColor: init.strokeColor,
                                                            strokeWidth: init.strokeWidth,
                                                            opacity: init.opacity,
                                                            paddingX: paddingX,
                                                            paddingY: init.paddingY,
                                                            borderRadius: init.borderRadius
                                                          }
                                                        });
                                                  }),
                                                label: "Padding X",
                                                min: 0,
                                                max: 999,
                                                className: "w-full",
                                                adornmentClassName: adornmentClassName
                                              }),
                                          JsxRuntime.jsx(NumberInput.make, {
                                                value: style.background.paddingY,
                                                onChange: (function (paddingY) {
                                                    var init = style.background;
                                                    dispatch({
                                                          TAG: "SetBackground",
                                                          _0: {
                                                            color: init.color,
                                                            strokeColor: init.strokeColor,
                                                            strokeWidth: init.strokeWidth,
                                                            opacity: init.opacity,
                                                            paddingX: init.paddingX,
                                                            paddingY: paddingY,
                                                            borderRadius: init.borderRadius
                                                          }
                                                        });
                                                  }),
                                                label: "Padding Y",
                                                min: 0,
                                                max: 999,
                                                className: "w-full",
                                                adornmentClassName: adornmentClassName
                                              })
                                        ],
                                        className: Cx.cx([
                                              "rounded-xl focus-within:border-zinc-500 border transition-colors border-transparent grid grid-cols-4 gap-2 bg-white/5 p-3 w-full",
                                              style.showBackground ? "brightness-100" : "brightness-50 pointer-events-none"
                                            ])
                                      })
                                ],
                                className: "flex flex-col gap-1.5"
                              }),
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsx(ToggleSwitch.make, {
                                                labelId: "word-animation-title",
                                                enabled: style.showWordAnimation,
                                                onChange: (function (param) {
                                                    dispatch("ToggleWordAnimation");
                                                  })
                                              }),
                                          JsxRuntime.jsx("h3", {
                                                children: "Current word highlight",
                                                id: "word-animation-title"
                                              })
                                        ],
                                        className: "flex items-center gap-4"
                                      }),
                                  JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsxs("div", {
                                                        children: [
                                                          JsxRuntime.jsxs("label", {
                                                                children: [
                                                                  JsxRuntime.jsx(Outline.PaintBrushIcon, {
                                                                        className: "size-5"
                                                                      }),
                                                                  "Background"
                                                                ],
                                                                className: "text-base text-white flex items-center gap-2",
                                                                id: "word-anim-background"
                                                              }),
                                                          JsxRuntime.jsx(ToggleSwitch.make, {
                                                                labelId: "word-anim-background",
                                                                enabled: style.wordAnimation.showBackground,
                                                                onChange: (function (showBackground) {
                                                                    var init = style.wordAnimation;
                                                                    dispatch({
                                                                          TAG: "SetWordAnimation",
                                                                          _0: {
                                                                            showBackground: showBackground,
                                                                            background: init.background,
                                                                            showFont: init.showFont,
                                                                            font: init.font,
                                                                            showPop: init.showPop,
                                                                            pop: init.pop
                                                                          }
                                                                        });
                                                                  })
                                                              })
                                                        ],
                                                        className: "flex items-center justify-between"
                                                      }),
                                                  JsxRuntime.jsxs("div", {
                                                        children: [
                                                          JsxRuntime.jsx(Input.make, {
                                                                label: "Fill",
                                                                value: style.wordAnimation.background.color,
                                                                type_: "color",
                                                                className: "w-full col-span-1 flex-1",
                                                                onChange: (function (value) {
                                                                    var init = style.wordAnimation;
                                                                    var init$1 = style.wordAnimation.background;
                                                                    dispatch({
                                                                          TAG: "SetWordAnimation",
                                                                          _0: {
                                                                            showBackground: init.showBackground,
                                                                            background: {
                                                                              color: value,
                                                                              opacity: init$1.opacity,
                                                                              paddingX: init$1.paddingX,
                                                                              paddingY: init$1.paddingY,
                                                                              borderRadius: init$1.borderRadius
                                                                            },
                                                                            showFont: init.showFont,
                                                                            font: init.font,
                                                                            showPop: init.showPop,
                                                                            pop: init.pop
                                                                          }
                                                                        });
                                                                  })
                                                              }),
                                                          JsxRuntime.jsx(NumberInput.Float.make, {
                                                                value: style.wordAnimation.background.opacity,
                                                                onChange: (function (opacity) {
                                                                    var init = style.wordAnimation;
                                                                    var init$1 = style.wordAnimation.background;
                                                                    dispatch({
                                                                          TAG: "SetWordAnimation",
                                                                          _0: {
                                                                            showBackground: init.showBackground,
                                                                            background: {
                                                                              color: init$1.color,
                                                                              opacity: opacity,
                                                                              paddingX: init$1.paddingX,
                                                                              paddingY: init$1.paddingY,
                                                                              borderRadius: init$1.borderRadius
                                                                            },
                                                                            showFont: init.showFont,
                                                                            font: init.font,
                                                                            showPop: init.showPop,
                                                                            pop: init.pop
                                                                          }
                                                                        });
                                                                  }),
                                                                label: "Opacity",
                                                                min: 0.0,
                                                                max: 1.0,
                                                                step: 0.1,
                                                                className: "w-full col-span-1 flex-1"
                                                              }),
                                                          JsxRuntime.jsx(NumberInput.make, {
                                                                value: style.wordAnimation.background.borderRadius,
                                                                onChange: (function (borderRadius) {
                                                                    var init = style.wordAnimation;
                                                                    var init$1 = style.wordAnimation.background;
                                                                    dispatch({
                                                                          TAG: "SetWordAnimation",
                                                                          _0: {
                                                                            showBackground: init.showBackground,
                                                                            background: {
                                                                              color: init$1.color,
                                                                              opacity: init$1.opacity,
                                                                              paddingX: init$1.paddingX,
                                                                              paddingY: init$1.paddingY,
                                                                              borderRadius: borderRadius
                                                                            },
                                                                            showFont: init.showFont,
                                                                            font: init.font,
                                                                            showPop: init.showPop,
                                                                            pop: init.pop
                                                                          }
                                                                        });
                                                                  }),
                                                                label: "Radius",
                                                                min: 0,
                                                                max: 99,
                                                                className: "w-full col-span-1",
                                                                adornment: Caml_option.some(JsxRuntime.jsx(Icons.BorderRadiusIcon.make, {
                                                                          color: "white",
                                                                          className: "size-4"
                                                                        })),
                                                                adornmentClassName: "font-mono rounded-md bg-zinc-500 px-2.5 inset-y-0"
                                                              }),
                                                          JsxRuntime.jsx(NumberInput.make, {
                                                                value: style.wordAnimation.background.paddingX,
                                                                onChange: (function (paddingX) {
                                                                    var init = style.wordAnimation;
                                                                    var init$1 = style.wordAnimation.background;
                                                                    dispatch({
                                                                          TAG: "SetWordAnimation",
                                                                          _0: {
                                                                            showBackground: init.showBackground,
                                                                            background: {
                                                                              color: init$1.color,
                                                                              opacity: init$1.opacity,
                                                                              paddingX: paddingX,
                                                                              paddingY: init$1.paddingY,
                                                                              borderRadius: init$1.borderRadius
                                                                            },
                                                                            showFont: init.showFont,
                                                                            font: init.font,
                                                                            showPop: init.showPop,
                                                                            pop: init.pop
                                                                          }
                                                                        });
                                                                  }),
                                                                label: "Padding X",
                                                                min: 0,
                                                                max: 99,
                                                                className: "w-full col-span-2",
                                                                adornmentClassName: adornmentClassName
                                                              }),
                                                          JsxRuntime.jsx(NumberInput.make, {
                                                                value: style.wordAnimation.background.paddingY,
                                                                onChange: (function (paddingY) {
                                                                    var init = style.wordAnimation;
                                                                    var init$1 = style.wordAnimation.background;
                                                                    dispatch({
                                                                          TAG: "SetWordAnimation",
                                                                          _0: {
                                                                            showBackground: init.showBackground,
                                                                            background: {
                                                                              color: init$1.color,
                                                                              opacity: init$1.opacity,
                                                                              paddingX: init$1.paddingX,
                                                                              paddingY: paddingY,
                                                                              borderRadius: init$1.borderRadius
                                                                            },
                                                                            showFont: init.showFont,
                                                                            font: init.font,
                                                                            showPop: init.showPop,
                                                                            pop: init.pop
                                                                          }
                                                                        });
                                                                  }),
                                                                label: "Padding Y",
                                                                min: 0,
                                                                max: 99,
                                                                className: "w-full col-span-2",
                                                                adornmentClassName: adornmentClassName
                                                              })
                                                        ],
                                                        className: Cx.cx([
                                                              "grid grid-cols-4 gap-2 pl-7",
                                                              style.wordAnimation.showBackground ? "brightness-100" : "brightness-50 pointer-events-none"
                                                            ])
                                                      })
                                                ],
                                                className: "flex flex-col gap-1.5"
                                              }),
                                          JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsxs("div", {
                                                        children: [
                                                          JsxRuntime.jsxs("label", {
                                                                children: [
                                                                  JsxRuntime.jsx(Outline.LanguageIcon, {
                                                                        className: "size-5"
                                                                      }),
                                                                  "Font"
                                                                ],
                                                                className: "text-base text-white flex items-center gap-2",
                                                                id: "word-anim-font"
                                                              }),
                                                          JsxRuntime.jsx(ToggleSwitch.make, {
                                                                labelId: "word-anim-font",
                                                                enabled: style.wordAnimation.showFont,
                                                                onChange: (function (showFont) {
                                                                    var init = style.wordAnimation;
                                                                    dispatch({
                                                                          TAG: "SetWordAnimation",
                                                                          _0: {
                                                                            showBackground: init.showBackground,
                                                                            background: init.background,
                                                                            showFont: showFont,
                                                                            font: init.font,
                                                                            showPop: init.showPop,
                                                                            pop: init.pop
                                                                          }
                                                                        });
                                                                  })
                                                              })
                                                        ],
                                                        className: "flex items-center justify-between"
                                                      }),
                                                  JsxRuntime.jsxs("div", {
                                                        children: [
                                                          JsxRuntime.jsx(Input.make, {
                                                                label: "Color",
                                                                value: Core__Option.getOr(style.wordAnimation.font.color, style.color),
                                                                type_: "color",
                                                                className: "w-full col-span-2 flex-1",
                                                                onChange: (function (value) {
                                                                    var init = style.wordAnimation;
                                                                    var init$1 = style.wordAnimation.font;
                                                                    dispatch({
                                                                          TAG: "SetWordAnimation",
                                                                          _0: {
                                                                            showBackground: init.showBackground,
                                                                            background: init.background,
                                                                            showFont: init.showFont,
                                                                            font: {
                                                                              color: value,
                                                                              fontWeight: init$1.fontWeight
                                                                            },
                                                                            showPop: init.showPop,
                                                                            pop: init.pop
                                                                          }
                                                                        });
                                                                  })
                                                              }),
                                                          JsxRuntime.jsxs(React$1.Field, {
                                                                className: "col-span-2",
                                                                children: [
                                                                  JsxRuntime.jsx(Input.Label.make, {
                                                                        children: "Weight",
                                                                        className: "whitespace-nowrap"
                                                                      }),
                                                                  JsxRuntime.jsx(Combobox.make, {
                                                                        options: style.fontVariants,
                                                                        selected: Core__Option.getOr(style.wordAnimation.font.fontWeight, style.fontWeight),
                                                                        formatValue: formatFontWeight,
                                                                        setSelected: (function (value) {
                                                                            Core__Option.forEach(value, (function (fontWeight) {
                                                                                    var init = style.wordAnimation;
                                                                                    var init$1 = style.wordAnimation.font;
                                                                                    dispatch({
                                                                                          TAG: "SetWordAnimation",
                                                                                          _0: {
                                                                                            showBackground: init.showBackground,
                                                                                            background: init.background,
                                                                                            showFont: init.showFont,
                                                                                            font: {
                                                                                              color: init$1.color,
                                                                                              fontWeight: fontWeight
                                                                                            },
                                                                                            showPop: init.showPop,
                                                                                            pop: init.pop
                                                                                          }
                                                                                        });
                                                                                  }));
                                                                          }),
                                                                        filter: (function (value) {
                                                                            return function (item) {
                                                                              return formatFontWeight(item).toLowerCase().includes(value);
                                                                            };
                                                                          })
                                                                      })
                                                                ]
                                                              })
                                                        ],
                                                        className: Cx.cx([
                                                              "grid grid-cols-4 gap-2 pl-7",
                                                              style.wordAnimation.showFont ? "brightness-100" : "brightness-50 pointer-events-none"
                                                            ])
                                                      })
                                                ],
                                                className: "flex flex-col gap-1.5"
                                              }),
                                          JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsxs("div", {
                                                        children: [
                                                          JsxRuntime.jsxs("label", {
                                                                children: [
                                                                  JsxRuntime.jsx(Outline.ArrowsPointingOutIcon, {
                                                                        className: "size-5"
                                                                      }),
                                                                  "Pop"
                                                                ],
                                                                className: "text-base text-white flex items-center gap-2",
                                                                id: "word-anim-pop"
                                                              }),
                                                          JsxRuntime.jsx(ToggleSwitch.make, {
                                                                labelId: "word-anim-pop",
                                                                enabled: style.wordAnimation.showPop,
                                                                onChange: (function (showPop) {
                                                                    var init = style.wordAnimation;
                                                                    dispatch({
                                                                          TAG: "SetWordAnimation",
                                                                          _0: {
                                                                            showBackground: init.showBackground,
                                                                            background: init.background,
                                                                            showFont: init.showFont,
                                                                            font: init.font,
                                                                            showPop: showPop,
                                                                            pop: init.pop
                                                                          }
                                                                        });
                                                                  })
                                                              })
                                                        ],
                                                        className: "flex items-center justify-between"
                                                      }),
                                                  JsxRuntime.jsxs("div", {
                                                        children: [
                                                          JsxRuntime.jsxs("div", {
                                                                children: [
                                                                  JsxRuntime.jsx("span", {
                                                                        children: "Scale",
                                                                        className: "text-sm text-white/70"
                                                                      }),
                                                                  JsxRuntime.jsx("span", {
                                                                        children: (style.wordAnimation.pop.scale * 100.0 | 0).toString() + "%",
                                                                        className: "text-sm font-medium text-white"
                                                                      })
                                                                ],
                                                                className: "flex items-center justify-between"
                                                              }),
                                                          JsxRuntime.jsx(Slider.make, {
                                                                onValueChange: (function (percent) {
                                                                    var init = style.wordAnimation;
                                                                    dispatch({
                                                                          TAG: "SetWordAnimation",
                                                                          _0: {
                                                                            showBackground: init.showBackground,
                                                                            background: init.background,
                                                                            showFont: init.showFont,
                                                                            font: init.font,
                                                                            showPop: init.showPop,
                                                                            pop: {
                                                                              scale: percent / 100.0
                                                                            }
                                                                          }
                                                                        });
                                                                  }),
                                                                value: style.wordAnimation.pop.scale * 100.0 | 0,
                                                                min: 100,
                                                                max: 200,
                                                                step: 1,
                                                                className: "!-ml-1.5"
                                                              })
                                                        ],
                                                        className: Cx.cx([
                                                              "flex flex-col gap-2 pl-7",
                                                              style.wordAnimation.showPop ? "brightness-100" : "brightness-50 pointer-events-none"
                                                            ])
                                                      })
                                                ],
                                                className: "flex flex-col gap-1.5"
                                              })
                                        ],
                                        className: Cx.cx([
                                              "rounded-xl focus-within:border-zinc-500 border transition-colors border-transparent flex flex-col gap-3 bg-white/5 p-2 w-full",
                                              style.showWordAnimation ? "brightness-100" : "brightness-50 pointer-events-none"
                                            ])
                                      })
                                ],
                                className: "flex flex-col gap-1.5"
                              })
                        ],
                        className: "flex flex-col gap-6"
                      }),
                  className: "overflow-auto pb-6"
                });
    });

export {
  formatFontWeight ,
  adornmentClassName ,
  make ,
}
/* make Not a pure module */
