// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function useCanvasScale(elementRef, size) {
  React.useEffect((function () {
          Belt_Option.forEach(Caml_option.nullable_to_opt(elementRef.current), (function (canvasElement) {
                  var ctx = canvasElement.getContext("2d");
                  canvasElement.height = Js_math.floor(size.scaledHeight);
                  canvasElement.width = Js_math.floor(size.scaledWidth);
                  ctx.scale(size.scale, size.scale);
                }));
        }), [size]);
}

function tsToFrame(ts, size) {
  return ts * size.frameToPxRatio + 32;
}

var audio_height = 60;

var Canvas;

var Canvas2d;

export {
  audio_height ,
  Canvas ,
  Canvas2d ,
  useCanvasScale ,
  tsToFrame ,
}
/* react Not a pure module */
