// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as CanvasSize from "./canvasSize.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as EditorContext from "../EditorContext.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ControlsCanvas(props) {
  var size = props.size;
  var controlsCanvasRef = React.useRef(null);
  var editorContext = EditorContext.useEditorContext();
  editorContext.usePlayer();
  CanvasSize.useCanvasScale(controlsCanvasRef, size);
  return JsxRuntime.jsx("canvas", {
              ref: Caml_option.some(controlsCanvasRef),
              className: "absolute inset-0",
              style: {
                height: String(size.height) + "px",
                width: String(size.width) + "px"
              },
              height: String(Js_math.floor(size.height)) + "px",
              width: String(Js_math.floor(size.width)) + "px"
            });
}

var make = ControlsCanvas;

export {
  make ,
}
/* react Not a pure module */
