// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Decode from "./codecs/Decode.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var canvasRef = React.useRef(null);
  var onChange = function (e) {
    var file = Belt_Array.getExn(e.currentTarget.files, 0);
    Core__Option.map(Caml_option.nullable_to_opt(canvasRef.current), (function (canvas) {
            Decode.start({
                  dataUri: file,
                  canvas: canvas,
                  setStatus: (function (status) {
                      console.log(status);
                    })
                });
          }));
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("canvas", {
                      ref: Caml_option.some(canvasRef),
                      height: "400",
                      width: "400"
                    }),
                JsxRuntime.jsx("input", {
                      accept: "video/*",
                      type: "file",
                      onChange: onChange
                    }),
                JsxRuntime.jsx("div", {
                      children: "This fucking hard",
                      className: "p-6"
                    })
              ],
              className: "text-black"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
